[package]
name = "rust-wasm-pong"
version = "0.0.1"
authors = ["Terkwood <metaterkhorn@gmail.com>"]
edition = "2018"

[dependencies]
#futures-channel-preview = "0.3.0-alpha.13"
#futures-util-preview =  "0.3.0-alpha.13"
#futures-executor-preview = "0.3.0-alpha.13"
lazy_static = "1.3.0"
stdweb = { git = "https://github.com/koute/stdweb", features = ["experimental_features_which_may_break_on_minor_version_bumps"] }
futures-preview = "0.3.0-alpha.13"

[profile.release]
lto = true
opt-level = 's' # optimize for size
