[package]
name = "rust-wasm-pong"
version = "0.0.1"
authors = ["Terkwood <metaterkhorn@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.3.0"
stdweb = "0.4"

[profile.release]
lto = true
opt-level = 's' # optimize for size
